import time

print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
print("loading...")
time.sleep(2)
